### ISSUE TITLE
PDF-A: Consider adding a Prerequisites section in the Examples section

### ISSUE THREAD

**Issue by jborbely** [apmp-dxfg/apmp-dxfg.github.io#1]
To help someone set up their computer to follow the [PDF-A Resource tutorial](https://github.com/apmp-dxfg/apmp-dxfg.github.io/tree/main/pages/dxfg/dxfg-pdfa-tut.md), perhaps a Prerequisites section could be added to the Examples section.

It could be something like the following rendered version _(I can open a PR for the raw Markdown code if this consideration sounds good -- and then make necessary changes from within the PR. Also, I will need to verify that the steps work from a fresh Windows 10 install. I didn't want to invest too much time if a Prerequisites sections is not desired.)_

### Prerequisites
This section describes how to set up your computer (Windows only) to have the necessary tools installed in order to follow these examples. [Python](https://www.python.org/), [Git](https://git-scm.com/) and [MiKTeX](https://miktex.org/) are required and the [github repository](https://github.com/apmp-dxfg/pdfa3-documents) will be cloned. If you already have Python, Git or MiKTeX (i.e., a TeX distribution that includes the `pdflatex` command) installed, then skip that installation step.

The following instructions assume that you have `WinGet` installed (the [Windows Package Manager](https://learn.microsoft.com/en-us/windows/package-manager/)). This is typically true for modern versions of Windows, as it is included with Windows 11 and Windows 10 May 2020 Update (version 2004) and later. If you don't have `WinGet` installed, you will need to configure these prerequisites another way.

Open a terminal (i.e., PowerShell or Command Prompt) then install Python (version 3.12 is shown, but you may install another version)
```console
> winget install --exact --id Python.Python.3.12
```
install Git
```console
> winget install --exact --id Git.Git
```
and install MiKTeX
```console
> winget install --exact --id MiKTeX.MiKTeX
```
You should now close your terminal and open a new terminal to allow the executable for these installed programs to be accessible.

Install the `pypdf` and `pikepdf` packages
```console
> pip install pypdf pikepdf
```
Finally, clone the repository and change directory, `cd`, into the `minimal` folder
```console
> git clone https://github.com/apmp-dxfg/pdfa3-documents.git
> cd pdfa3-documents/minimal
```

**Comment by jborbely** [comment]
@BlairDHall this is for you. I'm not sure who else is watching DXFG issues.

**Comment by BlairDHall** [comment]
@jborbely Thanks. This is a helpful initiative. Let's discuss a bit more and also get feedback from other DXFG members.

**Comment by jborbely** [comment]
Sounds good. I will open a PR as a draft _(for the primary reason to not misplace the Markdown syntax)_ and we can continue the discussion where appropriate (in this issue or in the PR).

Another option is to add something like the Prerequisites section to the README.md file in https://github.com/apmp-dxfg/pdfa3-documents rather than adding too much non-PDFA information to https://apmp-dxfg.org/dxfg-pdfa-tut

**Comment by BlairDHall** [comment]
I have added a new page with information about installing Python, LaTeX and git. The pages about PDF/A and checksum now link to this for furhter information.

**Comment by jborbely** [comment]
Sounds good. I will close the corresponding issue(s) and the PR draft.
