### ISSUE TITLE
PDF-A: Add sentence indicating which directory the example corresponds to

### ISSUE THREAD

**Issue by jborbely** [apmp-dxfg/apmp-dxfg.github.io#4]
I think that I may be helpful to mention which directory (in [pdfa3-document](https://github.com/apmp-dxfg/pdfa3-documents)) the corresponding files are located in, at the beginning of the `XMP` and `Calibration Reports in LaTeX` sections.

For XMP
https://github.com/apmp-dxfg/apmp-dxfg.github.io/blob/3565682a06d8c5899d6701361b065bdfa6fe9e3b/pages/dxfg/dxfg-pdfa-tut.md?plain=1#L166-L168

Mention that the source files are in [minimal-xmp](https://github.com/apmp-dxfg/pdfa3-documents/tree/main/minimal-xmp) 

For `Calibration Reports in LaTeX`
https://github.com/apmp-dxfg/apmp-dxfg.github.io/blob/3565682a06d8c5899d6701361b065bdfa6fe9e3b/pages/dxfg/dxfg-pdfa-tut.md?plain=1#L212-L214

Mention that the source files are in [LMI-report-cls](https://github.com/apmp-dxfg/pdfa3-documents/tree/main/LMI-report-cls)

**Comment by jborbely** [comment]
If #2 is considered to be a good idea, we could also include `cd` commands (within the same Markdown code-block for the `pdflatex` command) to help guide the reader to be able to run each command while reading the PDF-A resource.

**Comment by BlairDHall** [comment]
I will adopt the two suggestions to identify the sub directories on github

**Comment by jborbely** [comment]
Resolved in f043d29
