### ISSUE TITLE
PDF-A: Title Page Style suggestions

### ISSUE THREAD

**Issue by jborbely** [apmp-dxfg/apmp-dxfg.github.io#5]
1. Perhaps add a link to the [LMI-title-dev](https://github.com/apmp-dxfg/pdfa3-documents/tree/main/LMI-title-dev) repo in [Title Page Style](https://apmp-dxfg.org/dxfg-pdfa-tut-title-style#title-page-style)

2. Perhaps add a link to the [artwork](https://github.com/apmp-dxfg/pdfa3-documents/tree/main/artwork) repo in [Artwork](https://apmp-dxfg.org/dxfg-pdfa-tut-title-style#artwork), since the `LMI_cover.odt` file is not located in [LMI-title-dev](https://github.com/apmp-dxfg/pdfa3-documents/tree/main/LMI-title-dev)

3. Spelling: "Everything **t**hat" (missing "t") https://github.com/apmp-dxfg/apmp-dxfg.github.io/blob/e7bf0e2056fa3d3643c4cb2134ca369687225c0e/pages/dxfg/dxfg-pdfa-tut-title-style.md?plain=1#L29

4. Perhaps move https://github.com/apmp-dxfg/pdfa3-documents/blob/fe79768c34e84132e2cb9cce278b289ccacae7e6/LMI-title-dev/dev_title.tex#L42-L46 to come before https://github.com/apmp-dxfg/pdfa3-documents/blob/fe79768c34e84132e2cb9cce278b289ccacae7e6/LMI-title-dev/dev_title.tex#L34
so that the order that is described in the Resource page corresponds to the order in the `dev_title.tex` file.

5. Perhaps put the [Header, footer and page numbers](https://apmp-dxfg.org/dxfg-pdfa-tut-title-style#header-footer-and-page-numbers) section before the [Assembling the title page](https://apmp-dxfg.org/dxfg-pdfa-tut-title-style#assembling-the-title-page) section, since this is the order which things are defined in `dev_title.tex`. The [Header, footer and page numbers](https://apmp-dxfg.org/dxfg-pdfa-tut-title-style#header-footer-and-page-numbers) section isn't part of `\maketitlepage` so the location in the Resources file seems out of place.

**Comment by BlairDHall** [comment]
Thanks. All done. Uploading now.

**Comment by jborbely** [comment]
Looks good.

A few minor spelling/grammar suggestions that I missed in the latex comments

1. No suggestion on how to rephrase it, but the "composes shows" could be rephrased.  https://github.com/apmp-dxfg/apmp-dxfg.github.io/blob/14ac754051f1846bf332b96d4d0f0945d0498beb/pages/dxfg/dxfg-pdfa-tut-title-style.md?plain=1#L70
2. "compiler" https://github.com/apmp-dxfg/apmp-dxfg.github.io/blob/14ac754051f1846bf332b96d4d0f0945d0498beb/pages/dxfg/dxfg-pdfa-tut-title-style.md?plain=1#L80

and whatever changes are made in `dxfg-pdfa-tut-title-style.md` should be made in [dev_title.tex](https://github.com/apmp-dxfg/pdfa3-documents/blob/main/LMI-title-dev/dev_title.tex)

3. "is loaded AND? the page" https://github.com/apmp-dxfg/apmp-dxfg.github.io/blob/14ac754051f1846bf332b96d4d0f0945d0498beb/pages/dxfg/dxfg-pdfa-tut-title-style.md?plain=1#L285

**Comment by BlairDHall** [comment]
OK, I've made those changes. I also removed the 'currently being written' warning.

**Comment by jborbely** [comment]
Great!
