### ISSUE TITLE
PDF-A: Report Body Style Development suggestions

### ISSUE THREAD

**Issue by jborbely** [apmp-dxfg/apmp-dxfg.github.io#6]
1. Perhaps add a link to [LMI-body-dev](https://github.com/apmp-dxfg/pdfa3-documents/tree/main/LMI-body-dev) in the [LaTeX file for report body](https://apmp-dxfg.org/dxfg-pdfa-tut-body-style#latex-file-for-report-body) section.

2. "compiler" https://github.com/apmp-dxfg/apmp-dxfg.github.io/blob/8116f6ab1411dff8039c2ae98c8b91c4cbef55c2/pages/dxfg/dxfg-pdfa-tut-body-style.md?plain=1#L78

3. "Suppress" https://github.com/apmp-dxfg/apmp-dxfg.github.io/blob/8116f6ab1411dff8039c2ae98c8b91c4cbef55c2/pages/dxfg/dxfg-pdfa-tut-body-style.md?plain=1#L97
https://github.com/apmp-dxfg/apmp-dxfg.github.io/blob/8116f6ab1411dff8039c2ae98c8b91c4cbef55c2/pages/dxfg/dxfg-pdfa-tut-body-style.md?plain=1#L345

4. "there ARE more" https://github.com/apmp-dxfg/apmp-dxfg.github.io/blob/8116f6ab1411dff8039c2ae98c8b91c4cbef55c2/pages/dxfg/dxfg-pdfa-tut-body-style.md?plain=1#L227

5. closing "}" is missing in \begin{document} https://github.com/apmp-dxfg/apmp-dxfg.github.io/blob/8116f6ab1411dff8039c2ae98c8b91c4cbef55c2/pages/dxfg/dxfg-pdfa-tut-body-style.md?plain=1#L450

6. replace "tabularThere" with "There" https://github.com/apmp-dxfg/apmp-dxfg.github.io/blob/8116f6ab1411dff8039c2ae98c8b91c4cbef55c2/pages/dxfg/dxfg-pdfa-tut-body-style.md?plain=1#L479

7. "\`cols\` ~~is define~~ DEFINES" https://github.com/apmp-dxfg/apmp-dxfg.github.io/blob/8116f6ab1411dff8039c2ae98c8b91c4cbef55c2/pages/dxfg/dxfg-pdfa-tut-body-style.md?plain=1#L485

8. I wasn't completely sure what you are trying to say here &ndash; "So two lines table headings, and a horizontal line at the bottom, are created by" &ndash; but I think something like "So, a table with a three-line header followed by a horizontal line is created by"  https://github.com/apmp-dxfg/apmp-dxfg.github.io/blob/8116f6ab1411dff8039c2ae98c8b91c4cbef55c2/pages/dxfg/dxfg-pdfa-tut-body-style.md?plain=1#L487

9. "closing the ~~array and maths environments~~ tabular environment" https://github.com/apmp-dxfg/apmp-dxfg.github.io/blob/8116f6ab1411dff8039c2ae98c8b91c4cbef55c2/pages/dxfg/dxfg-pdfa-tut-body-style.md?plain=1#L504

10. "\end{tabular}" https://github.com/apmp-dxfg/apmp-dxfg.github.io/blob/8116f6ab1411dff8039c2ae98c8b91c4cbef55c2/pages/dxfg/dxfg-pdfa-tut-body-style.md?plain=1#L521

**Comment by BlairDHall** [comment]
Thanks. All done. I have synchronised with the source file on github. I will also remove the warning at the top.

**Comment by jborbely** [comment]
Found a few more.

1. "can BE specified" https://github.com/apmp-dxfg/apmp-dxfg.github.io/blob/c2f1f8ad0182c20e602d7b33fe52583a094df2e6/pages/dxfg/dxfg-pdfa-tut-body-style.md?plain=1#L20
2. "were already ~~been~~ discussed" https://github.com/apmp-dxfg/apmp-dxfg.github.io/blob/c2f1f8ad0182c20e602d7b33fe52583a094df2e6/pages/dxfg/dxfg-pdfa-tut-body-style.md?plain=1#L25
3. "importing ~~for~~ THE following" https://github.com/apmp-dxfg/apmp-dxfg.github.io/blob/c2f1f8ad0182c20e602d7b33fe52583a094df2e6/pages/dxfg/dxfg-pdfa-tut-body-style.md?plain=1#L288

**Comment by BlairDHall** [comment]
Thanks. All done.
