### ISSUE TITLE
PDF-A: Lunar Metrology Institute Style suggestions

### ISSUE THREAD

**Issue by jborbely** [apmp-dxfg/apmp-dxfg.github.io#7]
Nice overview of the LaTeX class file.

1. link in [github respository] is broken https://github.com/apmp-dxfg/apmp-dxfg.github.io/blob/c2f1f8ad0182c20e602d7b33fe52583a094df2e6/pages/dxfg/dxfg-pdfa-tut-report-style.md?plain=1#L20

2. "LaTeX" https://github.com/apmp-dxfg/apmp-dxfg.github.io/blob/c2f1f8ad0182c20e602d7b33fe52583a094df2e6/pages/dxfg/dxfg-pdfa-tut-report-style.md?plain=1#L60

3. "compiler" (FYI, in previous corrections for this typo in other Resource pages, the corrected word still ends with "ier" whereas it should end with "er") https://github.com/apmp-dxfg/apmp-dxfg.github.io/blob/c2f1f8ad0182c20e602d7b33fe52583a094df2e6/pages/dxfg/dxfg-pdfa-tut-report-style.md?plain=1#L71

4. "Suppress" https://github.com/apmp-dxfg/apmp-dxfg.github.io/blob/c2f1f8ad0182c20e602d7b33fe52583a094df2e6/pages/dxfg/dxfg-pdfa-tut-report-style.md?plain=1#L152

5. Remove leading ` character https://github.com/apmp-dxfg/apmp-dxfg.github.io/blob/c2f1f8ad0182c20e602d7b33fe52583a094df2e6/pages/dxfg/dxfg-pdfa-tut-report-style.md?plain=1#L275

**Comment by BlairDHall** [comment]
Done, thanks

**Comment by jborbely** [comment]
Looks great.

Feel free to remove the _not yet been reviewed_ note https://github.com/apmp-dxfg/apmp-dxfg.github.io/blob/3cd68d0664dd19962ff28a00bd20f6953d5b789b/pages/dxfg/dxfg-pdfa-tut-report-style.md?plain=1#L10

**Comment by BlairDHall** [comment]
Thanks for your careful review Jose. Much appreciated :-)
